version: "3"

services:
  miller.pub:
    container_name: miller.pub
    build:
      context: .
      dockerfile: ./web/miller.pub/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network
  readon.app:
    container_name: readon.app
    build:
      context: .
      dockerfile: ./web/readon.app/Dockerfile
    restart: always
    ports:
      - "3030:3000"
    networks:
      - app_network

networks:
  app_network:
    external: true