version: "3"

services:
  miller.pub:
    container_name: miller.pub
    build:
      context: .
      dockerfile: ./apps/miller.pub/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    external: true