import {
	AmazonwebservicesOriginalWordmark,
	AngularjsOriginal,
	CircleciPlain,
	CloudflareOriginal,
	Css3Original,
	DockerOriginal,
	ExpressOriginal,
	FigmaOriginal,
	GithubactionsOriginal,
	GithubOriginal,
	GitOriginal,
	GooglecloudOriginal,
	GraphqlPlain,
	HerokuOriginal,
	Html5Original,
	JavascriptOriginal,
	JestPlain,
	JiraOriginal,
	KubernetesOriginal,
	Link2Icon,
	MailIcon,
	MaterialuiOriginal,
	MongodbOriginal,
	MysqlOriginal,
	NestjsOriginal,
	NextjsOriginal,
	NodejsOriginal,
	PhpOriginal,
	PostgresqlOriginal,
	PrismaOriginal,
	PythonOriginal,
	ReactOriginal,
	RedisOriginal,
	ReduxOriginal,
	SiGithub,
	SiLinkedin,
	StorybookOriginal,
	TailwindcssOriginal,
	TypescriptOriginal,
} from '@lellimecnar/ui/icons';

export default {
	name: 'Lance Miller',
	title: 'Software Engineer',
	location: 'Remote – Loveland, CO',
	contacts: [
		{
			icon: <Link2Icon />,
			value: 'miller.pub',
			href: 'http://www.miller.pub',
		},
		{
			icon: <MailIcon />,
			value: 'lance@miller.pub',
			href: 'mailto:lance@miller.pub',
		},
		{
			icon: <SiLinkedin />,
			value: 'lellimecnar',
			href: 'https://linkedin.com/in/lellimecnar',
		},
		{
			icon: <SiGithub />,
			value: 'lellimecnar',
			href: 'https://github.com/lellimecnar',
		},
	],
	keywords: [
		'scrum',
		'agile',
		'scrum/agile',
		'agile/scrum',
		'html5',
		'html',
		'css',
		'less',
		'codeigniter',
		'lamp',
		'pyrocms',
		'magento',
		'wordpress',
		'js',
		'ux',
		'net',
		'rest',
		'api',
		'adobe',
		'photoshop',
		'ci',
		'cd',
		'ci/cd',
		'devops',
		'materialui',
		'next.js',
		'shadcn',
		'heroku',
		'aws',
		'architecture',
		'full-stack',
		'front-end',
		'back-end',
	],
	skills: [
		{
			name: 'React',
			score: 5,
			icon: <ReactOriginal />,
			category: 'Frameworks',
		},
		{
			name: 'TypeScript',
			score: 5,
			icon: <TypescriptOriginal />,
			category: 'Languages',
		},
		{
			name: 'JavaScript',
			score: 5,
			icon: <JavascriptOriginal />,
			category: 'Languages',
		},
		{
			name: 'CSS',
			score: 5,
			icon: <Css3Original />,
			category: 'Languages',
		},
		{
			name: 'HTML',
			score: 5,
			icon: <Html5Original />,
			category: 'Languages',
		},
		{
			name: 'TailwindCSS',
			score: 4.5,
			icon: <TailwindcssOriginal />,
			category: 'Libraries',
		},
		{
			name: 'shadcn/ui',
			score: 4.5,
			icon: (
				<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256">
					<rect width="256" height="256" fill="none" />
					<line
						x1="208"
						y1="128"
						x2="128"
						y2="208"
						fill="none"
						stroke="currentColor"
						strokeLinecap="round"
						strokeLinejoin="round"
						strokeWidth="16"
					/>
					<line
						x1="192"
						y1="40"
						x2="40"
						y2="192"
						fill="none"
						stroke="currentColor"
						strokeLinecap="round"
						strokeLinejoin="round"
						strokeWidth="16"
					/>
				</svg>
			),
			category: 'Libraries',
		},
		{
			name: 'Nx',
			score: 4,
			icon: (
				<svg
					viewBox="0 0 24 24"
					xmlns="http://www.w3.org/2000/svg"
					fill="rgb(14, 165, 233)"
				>
					<path d="m12 14.1-3.1 5-5.2-8.5v8.9H0v-15h3.7l5.2 8.9v-4l3 4.7zm.6-5.7V4.5H8.9v3.9h3.7zm5.6 4.1a2 2 0 0 0-2 1.3 2 2 0 0 1 2.4-.7c.4.2 1 .4 1.3.3a2.1 2.1 0 0 0-1.7-.9zm3.4 1c-.4 0-.8-.2-1.1-.6l-.2-.3a2.1 2.1 0 0 0-.5-.6 2 2 0 0 0-1.2-.3 2.5 2.5 0 0 0-2.3 1.5 2.3 2.3 0 0 1 4 .4.8.8 0 0 0 .9.3c.5 0 .4.4 1.2.5v-.1c0-.4-.3-.5-.8-.7zm2 1.3a.7.7 0 0 0 .4-.6c0-3-2.4-5.5-5.4-5.5a5.4 5.4 0 0 0-4.5 2.4l-1.5-2.4H8.9l3.5 5.4L9 19.5h3.6L14 17l1.6 2.4h3.5l-3.1-5a.7.7 0 0 1 0-.3 2.7 2.7 0 0 1 2.6-2.7c1.5 0 1.7.9 2 1.3.7.8 2 .5 2 1.5a.7.7 0 0 0 1 .6zm.4.2c-.2.3-.6.3-.8.6-.1.3.1.4.1.4s.4.2.6-.3V15z" />
				</svg>
			),
			category: 'Tools',
		},
		// {
		// 	name: 'SASS',
		// 	score: 5,
		// 	icon: <SassOriginal />,
		// 	category: 'Languages',
		// },
		// {
		// 	name: 'Styled Components',
		// 	score: 5,
		// 	icon: '',
		// 	category: 'Frameworks',
		// },
		{
			name: 'GraphQL',
			score: 4.5,
			icon: <GraphqlPlain />,
			category: 'Frameworks',
		},
		{
			name: 'Node.js',
			score: 5,
			icon: <NodejsOriginal />,
			category: 'Back-End',
		},
		{
			name: 'MongoDB',
			score: 4.5,
			icon: <MongodbOriginal />,
			category: 'Database',
		},
		{
			name: 'Prisma',
			score: 4,
			icon: <PrismaOriginal />,
			category: 'Libraries',
		},
		{
			name: 'Redux',
			score: 3.5,
			icon: <ReduxOriginal />,
			category: 'Libraries',
		},
		{
			name: 'Git',
			score: 4.5,
			icon: <GitOriginal />,
			category: 'Tools',
		},
		{
			name: 'Docker',
			score: 4.5,
			icon: <DockerOriginal />,
			category: 'Tools',
		},
		{
			name: 'Redis',
			score: 3,
			icon: <RedisOriginal />,
			category: 'Frameworks',
		},
		{
			name: 'PHP',
			score: 2.5,
			icon: <PhpOriginal />,
			category: 'Languages',
		},
		{
			name: 'MySQL',
			score: 4,
			icon: <MysqlOriginal />,
			category: 'Database',
		},
		{
			name: 'Python',
			score: 0.5,
			icon: <PythonOriginal />,
			category: 'Languages',
		},
		{
			name: 'Storybook',
			score: 4.5,
			icon: <StorybookOriginal />,
			category: 'Tools',
		},
		// {
		// 	name: 'Bash',
		// 	score: 4,
		// 	icon: <BashOriginal />,
		// 	category: 'Tools',
		// },
		{
			name: 'CircleCI',
			score: 3,
			icon: <CircleciPlain />,
			category: 'Tools',
		},
		{
			name: 'Express',
			score: 5,
			icon: <ExpressOriginal />,
			category: 'Back-End',
		},
		{
			name: 'Kubernetes',
			score: 1.5,
			icon: <KubernetesOriginal />,
			category: 'Tools',
		},
		{
			name: 'Jest',
			score: 5,
			icon: <JestPlain />,
			category: 'Frameworks',
		},
		// {
		// 	name: 'jQuery',
		// 	score: 5,
		// 	icon: <JqueryOriginal />,
		// 	category: 'Libraries',
		// },
		// {
		// 	name: 'LESS',
		// 	score: 3,
		// 	icon: <LessPlainWordmark />,
		// 	category: 'Languages',
		// },
		// {
		// 	name: 'Meteor',
		// 	score: 2.5,
		// 	icon: <MeteorOriginal />,
		// 	category: 'Frameworks',
		// },
		// {
		// 	name: 'Vagrant',
		// 	score: 2.25,
		// 	icon: <VagrantOriginal />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'Webpack',
		// 	score: 5,
		// 	icon: <WebpackOriginal />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'Gulp',
		// 	score: 5,
		// 	icon: <GulpPlain />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'NPM',
		// 	score: 5,
		// 	icon: <NpmOriginalWordmark />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'Yarn',
		// 	score: 5,
		// 	icon: <YarnOriginal />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'Stylus',
		// 	score: 5,
		// 	icon: <StylusOriginal />,
		// 	category: 'Languages',
		// },
		{
			name: 'Angular',
			score: 2.5,
			icon: <AngularjsOriginal />,
			category: 'Frameworks',
		},
		// {
		// 	name: 'Babel',
		// 	score: 5,
		// 	icon: <BabelOriginal />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'ESlint',
		// 	score: 5,
		// 	icon: <EslintOriginal />,
		// 	category: 'Tools',
		// },
		// {
		// 	name: 'CodeIgniter',
		// 	score: 1.5,
		// 	icon: <CodeigniterPlain />,
		// 	category: 'Frameworks',
		// },
		// {
		// 	name: 'Laravel',
		// 	score: 0.75,
		// 	icon: <LaravelOriginal />,
		// 	category: 'Frameworks',
		// },
		{
			name: 'Material UI',
			score: 4.5,
			icon: <MaterialuiOriginal />,
			category: 'Libraries',
		},
		// {
		// 	name: 'Markdown',
		// 	score: 5,
		// 	icon: <MarkdownOriginal />,
		// 	category: 'Languages',
		// },
		// {
		// 	name: 'Nginx',
		// 	score: 3.25,
		// 	icon: <NginxOriginal />,
		// 	category: 'Back-End',
		// },
		// {
		// 	name: 'Magento',
		// 	score: 0.5,
		// 	icon: <MagentoOriginal />,
		// 	category: 'Frameworks',
		// },
		// {
		// 	name: 'WordPress',
		// 	score: 1.5,
		// 	icon: <WordpressOriginal />,
		// 	category: 'Frameworks',
		// },
		// {
		// 	name: 'Adobe Photoshop',
		// 	score: 5,
		// 	icon: <PhotoshopOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'Adobe Illustrator',
		// 	score: 3.75,
		// 	icon: <IllustratorPlain />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'Adobe Premiere',
		// 	score: 2,
		// 	icon: <PremiereproOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'Adobe After Effects',
		// 	score: 2.75,
		// 	icon: <AftereffectsOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'IntelliJ',
		// 	score: 3.5,
		// 	icon: <IntellijOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'Maya',
		// 	score: 1.5,
		// 	icon: <MayaOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'VS Code',
		// 	score: 5,
		// 	icon: <VscodeOriginal />,
		// 	category: 'Software',
		// },
		// {
		// 	name: 'Bootstrap',
		// 	score: 5,
		// 	icon: <BootstrapOriginal />,
		// 	category: 'Libraries',
		// },
		{
			name: 'Jira',
			score: 3.5,
			icon: <JiraOriginal />,
			category: 'Software',
		},
		{
			name: 'GitHub',
			score: 5,
			icon: <GithubOriginal />,
			category: 'Software',
		},
		{
			name: 'Figma',
			score: 2.5,
			icon: <FigmaOriginal />,
			category: 'Software',
		},
		{
			name: 'AWS',
			score: 3,
			icon: <AmazonwebservicesOriginalWordmark />,
			category: 'Software',
		},
		{
			name: 'CloudFlare',
			score: 4,
			icon: <CloudflareOriginal />,
			category: 'Software',
		},
		{
			name: 'PostgreSQL',
			score: 3.5,
			icon: <PostgresqlOriginal />,
			category: 'Database',
		},
		// {
		// 	name: 'Apache',
		// 	score: 0.75,
		// 	icon: <ApacheOriginal />,
		// 	category: 'Back-End',
		// },
		// {
		// 	name: 'SQLite',
		// 	score: 2.25,
		// 	icon: <SqliteOriginal />,
		// 	category: 'Database',
		// },
		// {
		// 	name: 'Java',
		// 	score: 0.5,
		// 	icon: <JavaOriginal />,
		// 	category: 'Languages',
		// },
		{
			name: 'Next.js',
			score: 4,
			icon: <NextjsOriginal />,
			category: 'Frameworks',
		},
		{
			name: 'NestJS',
			score: 3,
			icon: <NestjsOriginal />,
			category: 'Frameworks',
		},
		{
			name: 'Heroku',
			score: 4.5,
			icon: <HerokuOriginal />,
			category: 'Software',
		},
		{
			name: 'Google Cloud',
			score: 4,
			icon: <GooglecloudOriginal />,
			category: 'Software',
		},
		{
			name: 'GitHub Actions',
			score: 4,
			icon: <GithubactionsOriginal />,
			category: 'Tools',
		},
	],
	experience: [
		{
			title: 'Software Engineer',
			employer: 'Foster Source',
			type: 'freelance',
			city: 'Westminster',
			state: 'CO',
			startDate: '2024/04/18',
			items: [
				'Took over an unfinished/abandoned project originally written in Angular and Express.js.',
				'Planned and implemented a complete rewrite using Next.js, TailwindCSS, MongoDB, Prisma, shadcn, TailwindCSS, etc.',
				'Setup new CI/CD pipeline with GitHub Actions and Heroku.',
				'Created new email workflow for users to communicate privately without exposing contact information.',
				'Designed a new registration workflow to improve user experience and data integrity.',
			],
		},
		{
			title: 'Senior Software Engineer',
			employer: 'Goosehead Insurance',
			city: 'Westlake',
			state: 'TX',
			startDate: '2023/03/09',
			endDate: '2023/11/3',
			items: [
				'Worked across several internal and external teams to deliver a complex project with uncertain or limited definition and tight deadlines.',
				'Worked in an Enterprise Architecture Team to identify and alleviate developer painpoints and productivity roadblocks.',
				'Proposed and implemented architectural improvements, enabling a single team to accomplish in weeks what had taken months for multiple teams.',
				'Built out several internal tools and libraries to increase developer productivity and performance.',
				'Helped train junior engineers during code reviews, pair coding sessions, and developer roundtable meetings.',
			],
		},
		{
			title: 'Senior Software Engineer',
			employer: 'CaucusRoom',
			type: '3/21–9/21: contract',
			city: 'Golden',
			state: 'CO',
			startDate: '2021/03/01',
			endDate: '2023/01/04',
			items: [
				'Worked in a start-up environment on a social web app using React, Node, GraphQL, MongoDB, and TypeScript.',
				'Optimized and improved accuracy of non-performant MongoDB queries.',
				'Set up a Storybook instance for component discovery and documentation.',
				'Optimized Apollo GraphQL cache configuration to improve data consistency and reduce unnecessary network calls.',
				'Refactored notification service to more correctly and efficiently manage events using Redis.',
			],
		},
		{
			title: 'Full Stack Developer',
			employer: 'Nutrien Ag Solutions',
			type: 'contract',
			city: 'Loveland',
			state: 'CO',
			startDate: '2020/05',
			endDate: '2021/02',
			items: [
				'Worked in a Scrum team on a mission-critical platform for managing very large customer orders, using React, Redux, MaterialUI, Node, MongoDB, GraphQL, TypeScript.',
				'Refactored a suite of utilities for converting units with very large numbers to accurately calculate pricing and measurements for custom product blends.',
			],
		},
		{
			title: 'Software Engineer - Front-End',
			employer: 'BambooHR',
			city: 'Lehi',
			state: 'UT',
			startDate: '2015/06',
			endDate: '2020/04',
			items: [
				'Worked in a Scrum team to develop customer and developer facing tools, utilities, components, and features in a SaaS web app using React, PHP, and MySQL.',
				'Led several training sessions on a variety of topics such as unit testing, React component testing, coding standards, etc.',
				'Served as tech-lead on several full-stack projects, communicating with product teams, UX, and both front-end and back-end engineers.',
				'Participated in a "Front-End Architecture Guild" to research and pursue solutions to department-wide front-end architectural needs.',
				'Championed an effort to modernize the front-end tech stack, from raw JS files to a fully automated build system with testing, linting, and deployment.',
				'Coordinated directly with DevOps to implement CI/CD optimizations and improvements such as decreasing build times, and streamlining the deployment process.',
				'Collaborated with a specialized guild to implement a new design system and component library in a monorepo using React, TypeScript, Storybook, etc.',
				'Contributed to a specialized Scrum team which focused primarily on tech debt.',
			],
		},
		{
			title: 'Software Engineer',
			employer: 'SpotXchange',
			city: 'Broomfield',
			state: 'CO',
			startDate: '2014/08',
			endDate: '2015/02',
			items: [
				'Worked in a Scrum team to maintain a set of large, high-availability, high-traffic, mission-critical applications with a legacy PHP code base.',
				'Helped in the conversion from an old MooTools front-end to use Angular and uiRouter.',
				'Wrote several Python scripts to aid in administrative tasks.',
			],
		},
		{
			title: 'UI/UX Developer',
			employer: 'Orange Soda',
			type: 'contract',
			city: 'American Fork',
			state: 'UT',
			startDate: '2014/01',
			endDate: '2014/10',
			items: [
				'Designed and developed a new finance portal front-end for internal use, using Angular & LESS in a Scrum/Agile team.',
				'Coordinated with .NET engineers to make required updates to an existing REST API.',
			],
		},
		{
			title: 'Software Developer',
			employer: 'LDS Church',
			type: 'contract',
			city: 'Riverton',
			state: 'UT',
			startDate: '2013/05',
			endDate: '2014/01',
			items: [
				'Used JavaScript and CSS/SASS in a Scrum/Agile team to enhance and maintain a data-intensive HTML5 PhoneGap app for internal use.',
				'Developed an entirely new dashboard with an interactive calendar and contact list for the app.',
			],
		},
		{
			title: 'Manager of Web Development',
			employer: 'Arena Communications',
			city: 'Salt Lake City',
			state: 'UT',
			startDate: '2012/06',
			endDate: '2013/02',
			items: [
				'Communicated directly with company executives to roadmap the technical needs of the new online department.',
				'Designed, developed, and maintained several PHP (CodeIgniter) websites for political clients.',
				'Managed traditional LAMP and cloud-based servers.',
			],
		},
		{
			title: 'Web Designer & Developer',
			employer: 'ThoughtLab',
			city: 'Salt Lake City',
			state: 'UT',
			startDate: '2010/06',
			endDate: '2012/06',
			items: [
				'Designed and developed PHP websites and blogs, using CodeIgniter, PyroCMS, Magento, and WordPress.',
				'Worked in a Scrum-like team for some larger .NET-based projects.',
				'Used Adobe Photoshop to design logos, websites, blogs, and other client assets.',
			],
		},
		{
			title: 'Graphic & Web Designer',
			employer: 'Heritage Web Solutions',
			type: 'contract',
			city: 'Provo',
			state: 'UT',
			startDate: '2009/07',
			endDate: '2010/01',
			items: [
				'Updated and maintained existing PHP websites.',
				'Designed company logos.',
			],
		},
	],
};
