import { type Family } from ".";

export const colors = [
  { family: "BR", sequence: "1", name: "Raw Umber" },
  { family: "BR", sequence: "2", name: "Potato Brown" },
  { family: "BR", sequence: "3", name: "Rose Beige" },
  { family: "BR", sequence: "208", name: "Black Brown" },
  { family: "E", sequence: "010", name: "Pale Fruit Pink" },
  { family: "E", sequence: "020", name: "Cotton Pearl" },
  { family: "E", sequence: "030", name: "Pink Flamingo" },
  { family: "E", sequence: "050", name: "Lipstick Natural" },
  { family: "E", sequence: "060", name: "Light Mahogany" },
  { family: "E", sequence: "070", name: "Brown" },
  { family: "E", sequence: "080", name: "Praline" },
  { family: "E", sequence: "090", name: "Eggshell White" },
  { family: "E", sequence: "110", name: "Dark Suntan" },
  { family: "E", sequence: "120", name: "Reddish Brass" },
  { family: "E", sequence: "130", name: "Copper" },
  { family: "E", sequence: "160", name: "Soft Sun" },
  { family: "E", sequence: "170", name: "Caribe Cocoa" },
  { family: "E", sequence: "210", name: "Brick Beige" },
  { family: "E", sequence: "220", name: "Sand" },
  { family: "E", sequence: "240", name: "Chamoise" },
  { family: "E", sequence: "260", name: "Leather" },
  { family: "E", sequence: "280", name: "Sand White" },
  { family: "E", sequence: "300", name: "Clay" },
  { family: "E", sequence: "310", name: "Dark Brown" },
  { family: "E", sequence: "330", name: "Milky White" },
  { family: "E", sequence: "370", name: "Light Walnut" },
  { family: "E", sequence: "380", name: "Ash Rose" },
  { family: "E", sequence: "400", name: "Cocoa Brown" },
  { family: "E", sequence: "430", name: "Pecan" },
  { family: "E", sequence: "432", name: "Vert Celadon" },
  { family: "E", sequence: "434", name: "Dragon Well Tea" },
  { family: "E", sequence: "440", name: "Khaki" },
  { family: "E", sequence: "450", name: "Fennel Seed" },
  { family: "E", sequence: "460", name: "Military Olive" },
  { family: "E", sequence: "470", name: "Tea Rose" },
  { family: "E", sequence: "490", name: "Deep Orange" },
  { family: "Y", sequence: "010", name: "Primrose" },
  { family: "Y", sequence: "030", name: "Lemon Chiffon" },
  { family: "Y", sequence: "040", name: "Calamansi" },
  { family: "Y", sequence: "050", name: "Summer Lemon" },
  { family: "Y", sequence: "070", name: "Acid Yellow" },
  { family: "Y", sequence: "080", name: "Lightning Yellow" },
  { family: "Y", sequence: "090", name: "Deep Lemon" },
  { family: "Y", sequence: "1", name: "Pastel Yellow" },
  { family: "Y", sequence: "2", name: "Sunflower" },
  { family: "Y", sequence: "3", name: "Barium Yellow" },
  { family: "Y", sequence: "4", name: "Quince" },
  { family: "Y", sequence: "5", name: "Rouge Orange" },
  { family: "Y", sequence: "6", name: "Lemon Yellow" },
  { family: "Y", sequence: "7", name: "Dull Yellow" },
  { family: "Y", sequence: "8", name: "Olive Yellow" },
  { family: "Y", sequence: "9", name: "Yellow Ochre" },
  { family: "Y", sequence: "10", name: "Apricot" },
  { family: "Y", sequence: "11", name: "Brown Grey" },
  { family: "Y", sequence: "12", name: "Mahogany" },
  { family: "Y", sequence: "13", name: "Chestnut Brown" },
  { family: "Y", sequence: "110", name: "Grayish Yellow" },
  { family: "Y", sequence: "120", name: "Buttercup Yellow" },
  { family: "Y", sequence: "121", name: "Prmrose" },
  { family: "Y", sequence: "130", name: "Mustard" },
  { family: "Y", sequence: "140", name: "Nugget" },
  { family: "Y", sequence: "145", name: "Buttercup Yellow" },
  { family: "Y", sequence: "150", name: "Grain Yellow" },
  { family: "Y", sequence: "180", name: "Shallow Orange Cafe" },
  { family: "Y", sequence: "210", name: "Deep Teak" },
  { family: "Y", sequence: "230", name: "Deep Cream" },
  { family: "Y", sequence: "250", name: "Flax" },
  { family: "Y", sequence: "260", name: "Yellow Dahlia" },
  { family: "Y", sequence: "270", name: "Pale Ochre" },
  { family: "YR", sequence: "030", name: "Carmine Red" },
  { family: "YR", sequence: "050", name: "Spring Orange" },
  { family: "YR", sequence: "070", name: "Light Orange" },
  { family: "YR", sequence: "090", name: "Peach Pie" },
  { family: "YR", sequence: "1", name: "Dark Yellow" },
  { family: "YR", sequence: "2", name: "Marigold" },
  { family: "YR", sequence: "3", name: "Orange" },
  { family: "YR", sequence: "4", name: "Salmon Pink" },
  { family: "YR", sequence: "5", name: "Terracotta" },
  { family: "YR", sequence: "6", name: "Primary Yellow" },
  { family: "YR", sequence: "7", name: "Cadmium Yellow" },
  { family: "YR", sequence: "8", name: "Salmon" },
  { family: "YR", sequence: "9", name: "Yellow Ochre" },
  { family: "YR", sequence: "10", name: "Brun" },
  { family: "YR", sequence: "20", name: "Morin" },
  { family: "YR", sequence: "33", name: "Melon Yellow" },
  { family: "YR", sequence: "34", name: "Yellow" },
  { family: "YR", sequence: "91", name: "Natural Oak" },
  { family: "YR", sequence: "92", name: "Chocolate" },
  { family: "YR", sequence: "95", name: "Burnt Sienna" },
  { family: "YR", sequence: "107", name: "Chrome Orange" },
  { family: "YR", sequence: "110", name: "Mellow Peach" },
  { family: "YR", sequence: "148", name: "Thin Persimmon" },
  { family: "YR", sequence: "170", name: "Chrome Orange" },
  { family: "YR", sequence: "172", name: "Tiger Lily" },
  { family: "YR", sequence: "180", name: "Lipstick Orange" },
  { family: "YR", sequence: "190", name: "Cadmium Orange" },
  { family: "YR", sequence: "205", name: "Powdery Orange" },
  { family: "YR", sequence: "209", name: "Hazelnuts" },
  { family: "YR", sequence: "212", name: "Milk White" },
  { family: "YR", sequence: "220", name: "Yellowish Shade" },
  { family: "YR", sequence: "230", name: "Light Reddish Yellow" },
  { family: "YR", sequence: "240", name: "Cream" },
  { family: "YR", sequence: "250", name: "Moccasin" },
  { family: "YR", sequence: "260", name: "Yellowish Brown" },
  { family: "R", sequence: "030", name: "Light Salmon Pink" },
  { family: "R", sequence: "050", name: "Chocolate Pink" },
  { family: "R", sequence: "070", name: "Agate" },
  { family: "R", sequence: "080", name: "Pale Cherry Pink" },
  { family: "R", sequence: "090", name: "Light Tea Rose" },
  { family: "R", sequence: "1", name: "Coral Pink" },
  { family: "R", sequence: "2", name: "Vermillion" },
  { family: "R", sequence: "3", name: "Coral Red" },
  { family: "R", sequence: "4", name: "Deep Red" },
  { family: "R", sequence: "5", name: "Cherry Pink" },
  { family: "R", sequence: "6", name: "Rose Red" },
  { family: "R", sequence: "7", name: "Old Red" },
  { family: "R", sequence: "8", name: "Geranium" },
  { family: "R", sequence: "9", name: "Pastel Rose" },
  { family: "R", sequence: "10", name: "Pastel Pink" },
  { family: "R", sequence: "11", name: "Mauve Shadow" },
  { family: "R", sequence: "12", name: "Rose Buvard" },
  { family: "R", sequence: "13", name: "Clematis" },
  { family: "R", sequence: "14", name: "Pale Purple" },
  { family: "R", sequence: "15", name: "Cerise" },
  { family: "R", sequence: "16", name: "Deep Violet" },
  { family: "R", sequence: "17", name: "Pansy" },
  { family: "R", sequence: "18", name: "Pastel Peach" },
  { family: "R", sequence: "19", name: "Barely Beige" },
  { family: "R", sequence: "20", name: "Powder Pink" },
  { family: "R", sequence: "21", name: "Fruit Pink" },
  { family: "R", sequence: "22", name: "Dark Blush" },
  { family: "R", sequence: "23", name: "Rose Pink" },
  { family: "R", sequence: "24", name: "Dark Violet Light" },
  { family: "R", sequence: "25", name: "Pale Blue Violet" },
  { family: "R", sequence: "26", name: "Honey" },
  { family: "R", sequence: "27", name: "Pale Mauve" },
  { family: "R", sequence: "28", name: "Colocassia Tonoimo" },
  { family: "R", sequence: "29", name: "Pear Color" },
  { family: "R", sequence: "30", name: "Pale Cherry Pink" },
  { family: "R", sequence: "100", name: "Blush" },
  { family: "R", sequence: "110", name: "Sardonyx" },
  { family: "R", sequence: "120", name: "Light Prawn" },
  { family: "R", sequence: "150", name: "Zinnober" },
  { family: "R", sequence: "160", name: "Cadmium Red" },
  { family: "R", sequence: "170", name: "Lipstick Red" },
  { family: "R", sequence: "180", name: "Bright Red" },
  { family: "R", sequence: "190", name: "Bougainvillaea" },
  { family: "R", sequence: "200", name: "Coral Essence" },
  { family: "R", sequence: "230", name: "Strong Red" },
  { family: "R", sequence: "240", name: "Garnet" },
  { family: "R", sequence: "242", name: "Greyish Cherry" },
  { family: "R", sequence: "250", name: "Antique Fusshcia" },
  { family: "R", sequence: "270", name: "Baby Blossoms" },
  { family: "R", sequence: "280", name: "Currant" },
  { family: "R", sequence: "282", name: "Colocasia Torino" },
  { family: "R", sequence: "284", name: "Clove" },
  { family: "R", sequence: "290", name: "Cardinal" },
  { family: "R", sequence: "340", name: "Argyle Purple" },
  { family: "R", sequence: "350", name: "Dark Purple Grey" },
  { family: "RV", sequence: "010", name: "Water Lily" },
  { family: "RV", sequence: "030", name: "Light Hot Pink" },
  { family: "RV", sequence: "050", name: "Lavender Pink" },
  { family: "RV", sequence: "070", name: "Sakura Pink" },
  { family: "RV", sequence: "080", name: "Bright Pink" },
  { family: "RV", sequence: "100", name: "Red Onion" },
  { family: "RV", sequence: "120", name: "Pale Pink" },
  { family: "RV", sequence: "130", name: "Queen Pink" },
  { family: "RV", sequence: "160", name: "Thistle" },
  { family: "RV", sequence: "180", name: "Hollycock" },
  { family: "RV", sequence: "200", name: "Dark Orchid" },
  { family: "RV", sequence: "240", name: "Bronze Purple" },
  { family: "RV", sequence: "250", name: "Peony" },
  { family: "RV", sequence: "260", name: "Pink Flamingo" },
  { family: "RV", sequence: "270", name: "Shadow Pink" },
  { family: "RV", sequence: "280", name: "Light Pink" },
  { family: "RV", sequence: "300", name: "Tender Pink" },
  { family: "RV", sequence: "320", name: "Apricot Pink" },
  { family: "RV", sequence: "330", name: "Strawberry Pink" },
  { family: "RV", sequence: "350", name: "Crimson" },
  { family: "RP", sequence: "1", name: "Vivid Reddish Purple" },
  { family: "RP", sequence: "6", name: "Vivid Pink" },
  { family: "V", sequence: "020", name: "Pale Lilac" },
  { family: "V", sequence: "030", name: "Mauve" },
  { family: "V", sequence: "050", name: "Pearl Violet" },
  { family: "V", sequence: "060", name: "Amethyst" },
  { family: "V", sequence: "070", name: "Eggplant Purple" },
  { family: "V", sequence: "080", name: "Dark Violet" },
  { family: "V", sequence: "090", name: "Deep Purple" },
  { family: "V", sequence: "140", name: "Begonia" },
  { family: "V", sequence: "150", name: "Mallow" },
  { family: "V", sequence: "160", name: "Deep Lilac" },
  { family: "V", sequence: "210", name: "Signal Violet" },
  { family: "V", sequence: "230", name: "Viola" },
  { family: "V", sequence: "250", name: "Light Lavender" },
  { family: "V", sequence: "270", name: "Lobelia" },
  { family: "V", sequence: "320", name: "Gentian Violet" },
  { family: "V", sequence: "322", name: "Rain Flower Purple" },
  { family: "V", sequence: "330", name: "Prune" },
  { family: "V", sequence: "340", name: "Lavender Blue" },
  { family: "V", sequence: "350", name: "Hydrangea Blue" },
  { family: "V", sequence: "370", name: "Blue Bell" },
  { family: "V", sequence: "390", name: "Dark Slate Blue" },
  { family: "V", sequence: "450", name: "Dark Lavender" },
  { family: "P", sequence: "1", name: "Vivid Purple" },
  { family: "P", sequence: "2", name: "Light Violet" },
  { family: "P", sequence: "3", name: "Pastel Violet" },
  { family: "P", sequence: "4", name: "Lavender" },
  { family: "P", sequence: "5", name: "Aubergine" },
  { family: "PB", sequence: "1", name: "Sky Blue" },
  { family: "PB", sequence: "2", name: "Brilliant Blue" },
  { family: "PB", sequence: "3", name: "Cobalt Blue" },
  { family: "PB", sequence: "4", name: "Napoleon Blue" },
  { family: "PB", sequence: "5", name: "Prussian Blue" },
  { family: "PB", sequence: "6", name: "Royal Blue" },
  { family: "PB", sequence: "7", name: "Pastel Blue" },
  { family: "PB", sequence: "8", name: "Cerulean Blue" },
  { family: "PB", sequence: "9", name: "Cloud Blue" },
  { family: "PB", sequence: "10", name: "Turqoise Green Light" },
  { family: "PB", sequence: "11", name: "Marine Blue" },
  { family: "B", sequence: "030", name: "Frost Blue" },
  { family: "B", sequence: "040", name: "Baby Blue" },
  { family: "B", sequence: "050", name: "Robin's Egg Blue" },
  { family: "B", sequence: "070", name: "Tahitian Blue" },
  { family: "B", sequence: "080", name: "Process Blue" },
  { family: "B", sequence: "090", name: "Pebble Blue" },
  { family: "B", sequence: "110", name: "Crystal Blue" },
  { family: "B", sequence: "120", name: "Pale Blue" },
  { family: "B", sequence: "140", name: "Aquamarine" },
  { family: "B", sequence: "150", name: "Phthalo Blue" },
  { family: "B", sequence: "170", name: "Hyacinth" },
  { family: "B", sequence: "180", name: "Vienna Blue" },
  { family: "B", sequence: "190", name: "Ultramarine" },
  { family: "B", sequence: "220", name: "Pale Grayish Blue" },
  { family: "B", sequence: "250", name: "Light Blue" },
  { family: "B", sequence: "260", name: "Smoky Blue" },
  { family: "B", sequence: "270", name: "Vivid Blue" },
  { family: "B", sequence: "290", name: "Antwerp Blue" },
  { family: "B", sequence: "300", name: "Marine Blue" },
  { family: "B", sequence: "340", name: "Lavender Mist" },
  { family: "B", sequence: "350", name: "Cornflower Blue" },
  { family: "B", sequence: "380", name: "Capri Blue" },
  { family: "B", sequence: "440", name: "Cyanine Blue" },
  { family: "B", sequence: "64", name: "Indian Blue" },
  { family: "BG", sequence: "1", name: "Turqoise Green" },
  { family: "BG", sequence: "2", name: "Deep Green" },
  { family: "BG", sequence: "3", name: "Blue Grey 3" },
  { family: "BG", sequence: "4", name: "Mint Blue" },
  { family: "BG", sequence: "5", name: "Dolphin Blue" },
  { family: "BG", sequence: "6", name: "Peacock Green" },
  { family: "BG", sequence: "7", name: "Forest Green" },
  { family: "BG", sequence: "8", name: "Teal" },
  { family: "BG", sequence: "9", name: "Pigeon Blue" },
  { family: "BG", sequence: "68", name: "Turquoise Blue" },
  { family: "G", sequence: "020", name: "Pale Lemon Yellow" },
  { family: "G", sequence: "030", name: "Crescent Yellow" },
  { family: "G", sequence: "050", name: "Celadon Green" },
  { family: "G", sequence: "060", name: "Celery Yellow" },
  { family: "G", sequence: "070", name: "Lemon Green" },
  { family: "G", sequence: "080", name: "Limade" },
  { family: "G", sequence: "1", name: "Emerald Green" },
  { family: "G", sequence: "2", name: "Vivid Green" },
  { family: "G", sequence: "3", name: "Ocean Green" },
  { family: "G", sequence: "4", name: "Mint Green Light" },
  { family: "G", sequence: "5", name: "Turquoise Ink Blue" },
  { family: "G", sequence: "6", name: "Dusty Jade Green" },
  { family: "G", sequence: "7", name: "Chromium Oxide Green" },
  { family: "G", sequence: "8", name: "Glass Green" },
  { family: "G", sequence: "9", name: "Meadow Green" },
  { family: "G", sequence: "110", name: "Mignonette" },
  { family: "G", sequence: "120", name: "Yellowish Green" },
  { family: "G", sequence: "130", name: "Acid Green" },
  { family: "G", sequence: "140", name: "Horseradish" },
  { family: "G", sequence: "150", name: "Lettuce Green" },
  { family: "G", sequence: "170", name: "May Green" },
  { family: "G", sequence: "190", name: "Olive Green" },
  { family: "G", sequence: "220", name: "Lime Green" },
  { family: "G", sequence: "230", name: "Willow" },
  { family: "G", sequence: "240", name: "Beige Green" },
  { family: "G", sequence: "260", name: "Apple Green" },
  { family: "G", sequence: "270", name: "Moss" },
  { family: "G", sequence: "300", name: "Dark Olive" },
  { family: "G", sequence: "320", name: "Jade Green" },
  { family: "G", sequence: "322", name: "Pale Aqua Mint" },
  { family: "G", sequence: "324", name: "Aqua Blue" },
  { family: "G", sequence: "326", name: "Bright Blue" },
  { family: "G", sequence: "330", name: "Mineral Green" },
  { family: "G", sequence: "340", name: "Horizon Green" },
  { family: "G", sequence: "360", name: "Pond Green" },
  { family: "G", sequence: "390", name: "Green" },
  { family: "G", sequence: "410", name: "Light Holly Green" },
  { family: "G", sequence: "420", name: "Green Shadow" },
  { family: "G", sequence: "440", name: "Leaf Green" },
  { family: "G", sequence: "470", name: "Pine Tree Green" },
  { family: "G", sequence: "490", name: "Viridian" },
  { family: "G", sequence: "500", name: "Peacock Blue" },
  { family: "GY", sequence: "1", name: "Pale Green" },
  { family: "GY", sequence: "2", name: "Grass Green" },
  { family: "GY", sequence: "3", name: "Bud Green" },
  { family: "GY", sequence: "4", name: "Yellow Green" },
  { family: "GY", sequence: "5", name: "Absinthe" },
  { family: "GY", sequence: "6", name: "Anise" },
  { family: "GY", sequence: "7", name: "Sugarcane" },
  { family: "GY", sequence: "8", name: "Petits Pois" },
  { family: "GY", sequence: "42", name: "Bronze Green" },
  { family: "GY", sequence: "43", name: "Deep Olive Green" },
  { family: "GY", sequence: "163", name: "Green Bice" },
  { family: "GY", sequence: "172", name: "Spectrum Green" },
  { family: "GY", sequence: "173", name: "Dim Green" },
  { family: "YG", sequence: "040", name: "Yellow Grey 04" },
  { family: "YG", sequence: "080", name: "Yellow Grey 08" },
  { family: "YG", sequence: "100", name: "Yellow Grey 100" },
  { family: "RG", sequence: "030", name: "Red Grey 03" },
  { family: "RG", sequence: "050", name: "Red Grey 05" },
  { family: "RG", sequence: "080", name: "Red Grey 08" },
  { family: "RG", sequence: "110", name: "Red Grey 11" },
  { family: "RG", sequence: "120", name: "Red Grey 12" },
  { family: "RG", sequence: "150", name: "Red Grey 15" },
  { family: "BG", sequence: "050", name: "Cool Grey 05" },
  { family: "BG", sequence: "060", name: "Deep Cool Grey" },
  { family: "BG", sequence: "070", name: "Cool Grey 07" },
  { family: "BGII", sequence: "03", name: "Blue Grey II 3" },
  { family: "BGII", sequence: "05", name: "Blue Grey II 5" },
  { family: "BGII", sequence: "09", name: "Blue Grey II 9" },
  { family: "MG", sequence: "020", name: "Blue Grey 02" },
  { family: "MG", sequence: "030", name: "Blue Grey 03" },
  { family: "MG", sequence: "060", name: "Blue Grey 06" },
  { family: "MG", sequence: "100", name: "Blue Grey 09" },
  { family: "GG", sequence: "020", name: "Green Grey 02" },
  { family: "GG", sequence: "040", name: "Light Jade Green Grey" },
  { family: "GG", sequence: "060", name: "Green Grey 06" },
  { family: "GG", sequence: "1", name: "Green Grey 1" },
  { family: "GG", sequence: "3", name: "Green Grey 3" },
  { family: "GG", sequence: "5", name: "Green Grey 5" },
  { family: "GG", sequence: "9", name: "Green Grey 9" },
  { family: "GG", sequence: "110", name: "Toner Grey" },
  { family: "WG", sequence: "0.5", name: "Warm Grey 0.5" },
  { family: "WG", sequence: "01", name: "Warm Grey 1" },
  { family: "WG", sequence: "09", name: "Warm Grey 9" },
  { family: "WG", sequence: "3", name: "Warm Grey 3" },
  { family: "WG", sequence: "4", name: "Warm Grey 4" },
  { family: "WG", sequence: "050", name: "Warm Grey 05" },
  { family: "WG", sequence: "070", name: "Warm Grey 07" },
  { family: "WG", sequence: "090", name: "Warm Grey 09" },
  { family: "WG", sequence: "130", name: "Warm Grey 13" },
  { family: "NG", sequence: "03", name: "Neutral Grey 3" },
  { family: "NG", sequence: "06", name: "Neutral Grey 6" },
  { family: "NG", sequence: "07", name: "Neutral Grey 7" },
  { family: "NG", sequence: "09", name: "Neutral Grey 9" },
  { family: "CG", sequence: "020", name: "Neutral Grey 02" },
  { family: "CG", sequence: "030", name: "Neutral Grey 03" },
  { family: "CG", sequence: "050", name: "Neutral Grey 05" },
  { family: "CG", sequence: "070", name: "Neutral Grey 07" },
  { family: "CG", sequence: "2", name: "Cool Grey II 2" },
  { family: "CG", sequence: "5", name: "Cool Grey II 5" },
  { family: "CGII", sequence: "00", name: "Cool Grey II 0" },
  { family: "CGII", sequence: "04", name: "Cool Grey II 4" },
  { family: "CGII", sequence: "07", name: "Cool Grey II 7" },
  { family: "CGII", sequence: "08", name: "Cool Grey II 8" },
  { family: "CGII", sequence: "09", name: "Cool Grey II 9" },
  { family: null, sequence: "120", name: "Black" },
  { family: null, sequence: "0", name: "Colorless Blender" },
  { family: "FY", sequence: "010", name: "Fluorescent Yellow" },
  { family: "FY", sequence: "020", name: "Fluorescent Orange" },
  { family: "FY", sequence: "030", name: "Fluorescent Red" },
  { family: "FY", sequence: "050", name: "Fluorescent Violet" },
] as const satisfies Readonly<
  {
    family: Family | null;
    sequence: string;
    name: string;
  }[]
>;

export type Color = (typeof colors)[number];

export type ColorId = Color extends infer C
  ? C extends {
      family: infer F;
      sequence: infer S;
    }
    ? S extends string
      ? F extends Family
        ? `${F}${S}`
        : `${S}`
      : never
    : never
  : never;
