export const families = {
  BR: "Brown",
  E: "Earth",
  Y: "Yellow",
  YR: "Yellow Red",
  R: "Red",
  RV: "Red Violet",
  RP: "Red Purple",
  V: "Violet",
  P: "Purple",
  PB: "Purple Blue",
  B: "Blue",
  BG: "Blue Green / Blue Grey",
  G: "Green",
  GY: "Green Yellow",
  YG: "Yellow Grey",
  RG: "Red Grey",
  BGII: "Blue Grey II",
  MG: "Mineral Grey",
  GG: "Green Grey",
  WG: "Warm Grey",
  NG: "Neutral Grey",
  CG: "Cool Grey",
  CGII: "Cool Grey II",
  N: "Neutral",
  FY: "Fluorescent",
} as const;

export type Family = keyof typeof families;
export type FamilyName = (typeof families)[Family];
