import type { UISpecSchema } from '@ui-spec/core';
import { readFile, writeFile } from 'node:fs/promises';

function inferTsType(value: unknown): string {
	if (value === null) return 'null';
	if (typeof value === 'string') return 'string';
	if (typeof value === 'number') return 'number';
	if (typeof value === 'boolean') return 'boolean';
	if (Array.isArray(value)) {
		const inner = value.length ? inferTsType(value[0]) : 'unknown';
		return `${inner}[]`;
	}
	if (value && typeof value === 'object') {
		const entries = Object.entries(value as any)
			.map(([k, v]) => `\t${k}: ${inferTsType(v)};`)
			.join('\n');
		return `{\n${entries}\n}`;
	}
	return 'unknown';
}

export async function generateTypesCommand(
	inputFile: string,
	outFile: string,
): Promise<void> {
	const raw = await readFile(inputFile, 'utf8');
	const schema = JSON.parse(raw) as UISpecSchema;
	const dataType = inferTsType(schema.data ?? {});

	const output = [
		`// Generated by @ui-spec/cli`,
		`export type UISpecData = ${dataType};`,
	].join('\n');

	await writeFile(outFile, output, 'utf8');
}
